#!/system/bin/sh

#Nos entropy Generator engine for Fly-On Mod™ by Slaid480
#Copyright (C) 2013 Jeffrey Gomez (Exit_Only)

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

#===============================================================#

FLY=/data/Fly-On/S08_rngd.log

busybox rm -f $FLY
busybox touch $FLY

echo "$( date +"%m-%d-%Y %H:%M:%S" ) Activating 'rngd' binary & setting 'rngd' binary values..." | tee -a $FLY

rngd -s 512 -t 1 -W 50
echo -16 > /proc/$(pgrep rngd)/oom_adj
renice 8 `pidof rngd`

echo "$( date +"%m-%d-%Y %H:%M:%S" ) 'rngd' binary is active & 'rngd' binary values are set to 'light' governor!!!" | tee -a $FLY