#!/system/bin/sh
# Touchscreen tweaks for  For Fly-On Mod™ by Slaid480!

#============ Copyright (C) 2015 Salah Abouabdallah(Slaid480)===========#
 
 see <http://www.gnu.org/licenses/>.
 
#=======================================================================#

FLY=/data/Fly-On/11touchscreen.log

busybox rm -f $FLY
busybox touch $FLY

echo "# Fly-On Mod™ LOGGING ENGINE" | tee -a $FLY
echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y %H:%M:%S" ) Forcing touch rendering..." | tee -a $FLY;

echo 11000 > /sys/class/touch/switch/set_touchscreen;
echo 13060 > /sys/class/touch/switch/set_touchscreen;
echo 14005 > /sys/class/touch/switch/set_touchscreen;
echo 7035 > /sys/class/touch/switch/set_touchscreen;
echo 8002 > /sys/class/touch/switch/set_touchscreen;

echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y %H:%M:%S" ) Touch rendering is done!" | tee -a $FLY;