#!/system/bin/sh
#============ Copyright (C) 2015 Salah Abouabdallah(Slaid480)===========#
 
 see <http://www.gnu.org/licenses/>.
 
#=======================================================================#

FLY=/data/Fly-On/12DNS.log;

busybox rm -f $FLY
busybox touch $FLY

if [ -e $FLY ]; then
	rm $FLY;
fi;

echo "# Fly-On Mod™ LOGGING ENGINE" | tee -a $FLY
echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y %H:%M:%S" )  executing 95DNS script..." | tee -a $FLY;

dnsproxy2dex -w 127.0.0.1 &

dnsmasqdex -C /system/etc/DNS_Fly-On/dnsmasq.conf

pixelservdex 127.0.0.1 >/dev/null 2>&1

echo "" | tee -a $FLY
echo "...Tweaking DsnMasq running successfully..." | tee -a $FLY
echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y %H:%M:%S" ) 95DNS Has been Successfully Executed..." | tee -a $FLY
