#!/system/bin/sh
# ===========================================
# ===========================================
# ========== Fly_core | Fly-On Mod™ =========
# ========== By Slaid480@XDA 2013 ===========
# ===========================================
# ===========================================


# VFS, VM,Kernel Tweaks

#sysctl -w kernel.sem="250 256000 32 1024";
#sysctl -w kernel.shmmax="$max";
#sysctl -w kernel.shmall="$all";
#sysctl -w kernel.msgmni=1024;

#echo $max > /proc/sys/kernel/shmmax;
#echo $all > /proc/sys/kernel/shmall;

if [ "$mem" -lt 524288 ];then
  sysctl -w vm.dirty_background_ratio=15;
  sysctl -w vm.dirty_ratio=30;
elif [ "$mem" -lt 1049776 ];then
  sysctl -w vm.dirty_background_ratio=10;
  sysctl -w vm.dirty_ratio=20;
else
  sysctl -w vm.dirty_background_ratio=5;
  sysctl -w vm.dirty_ratio=10;
fi;

sysctl -w vm.page-cluster=3;
sysctl -w vm.laptop_mode=0;
sysctl -w vm.dirty_expire_centisecs=3000;
sysctl -w vm.dirty_writeback_centisecs=500;
sysctl -w vm.vfs_cache_pressure=50;
sysctl -w vm.overcommit_memory=1;
sysctl -w vm.oom_kill_allocating_task=0;




# Tweaking processes at wake

#    renice -1 `pidof com.android.phone`;   
#    renice -1 `pidof com.android.mms`; # Text message app
#    renice -1 `pidof com.swype.android.inputmethod`; # Keyboard
#    renice -1 `pidof com.sec.android.app.controlpanel`; # Task manager
#    renice -1 `pidof com.android.systemui`; # Status bar
#    renice -1 `pidof com.android.settings`; # Settings menu
#    renice -1 `pidof com.android.vending`; # Market app
#    renice -1 `pidof com.sec.android.app.camera`; # Camera app
#    renice -1 `pidof android.process.acore`;
#    renice -1 `pidof kondemand/0`;
#    renice -1 `pidof ksmartass_up/0`;




# Network speed Tweaks

echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes;
echo "30" > /proc/sys/net/ipv4/tcp_keepalive_intvl;
echo "30" > /proc/sys/net/ipv4/tcp_fin_timeout;
echo "1" > /proc/sys/net/ipv4/tcp_moderate_rcvbuf;
echo "1" > /proc/sys/net/ipv4/route/flush;
echo "6144" > /proc/sys/net/ipv4/udp_rmem_min;
echo "6144" > /proc/sys/net/ipv4/udp_wmem_min;
echo "1" > /proc/sys/net/ipv4/tcp_rfc1337;
echo "0" > /proc/sys/net/ipv4/ip_no_pmtu_disc;
echo "0" > /proc/sys/net/ipv4/tcp_ecn;
echo "6144 87380 2097152" > /proc/sys/net/ipv4/tcp_wmem;
echo "6144 87380 2097152" > /proc/sys/net/ipv4/tcp_rmem;
echo "1" > /proc/sys/net/ipv4/tcp_fack;
echo "2" > /proc/sys/net/ipv4/tcp_synack_retries;
echo "2" > /proc/sys/net/ipv4/tcp_syn_retries;
echo "1" > /proc/sys/net/ipv4/tcp_no_metrics_save;
echo "1800" > /proc/sys/net/ipv4/tcp_keepalive_time;
echo "0" > /proc/sys/net/ipv4/ip_forward;
echo "1" > /proc/sys/net/ipv4/tcp_sack;
echo "1" > /proc/sys/net/ipv4/tcp_dsack;
echo "1" > /proc/sys/net/ipv4/tcp_tw_recycle;
echo "1" > /proc/sys/net/ipv4/tcp_window_scaling;
echo "0" > /proc/sys/net/ipv4/conf/default/accept_source_route;
echo "0" > /proc/sys/net/ipv4/conf/all/accept_source_route;
echo "0" > /proc/sys/net/ipv4/conf/all/accept_redirects;
echo "0" > /proc/sys/net/ipv4/conf/default/accept_redirects;
echo "0" > /proc/sys/net/ipv4/conf/all/secure_redirects;
echo "0" > /proc/sys/net/ipv4/conf/default/secure_redirects;
echo "0" > /proc/sys/net/ipv4/ip_dynaddr;
echo "0" > /proc/sys/net/ipv4/tcp_timestamps;
echo "1" > /proc/sys/net/ipv4/tcp_tw_reuse;
echo "1440000" > /proc/sys/net/ipv4/tcp_max_tw_buckets;
echo "57344 57344 524288" > /proc/sys/net/ipv4/tcp_mem;
echo "1440000" > /proc/sys/net/ipv4/tcp_max_tw_buckets;
echo "2097152" > /proc/sys/net/core/rmem_max;
echo "2097152" > /proc/sys/net/core/wmem_max;
echo "262144" > /proc/sys/net/core/rmem_default;
echo "262144" > /proc/sys/net/core/wmem_default;
echo "20480" > /proc/sys/net/core/optmem_max;
echo "2500" > /proc/sys/net/core/netdev_max_backlog;
echo "50" > /proc/sys/net/unix/max_dgram_qlen;






# Build.prop Tweaks

# Smoother Scrolling
setprop windowsmgr.max_events_per_sec 240
# Battery saving Tweaks
setprop ro.ril.disable.power.collapse 0
setprop pm.sleep_mode 1
setprop wifi.supplicant_scan_interval 150
#Graphics Tweaks and improvments
setprop ro.media.enc.hprof.vid.bps 8000000
setprop persist.sys.use_dithering 1
setprop ro.media.dec.jpeg.memcap 8000000
setprop debug.performance.tuning 1
setprop video.accelerate.hw 1
#kernel tweaks(Disable error checking)
setprop ro.kernel.android.checkjni 0




# Disable Gentle Fair Sleepers(Would Improve smoothness)
echo "NO_GENTLE_FAIR_SLEEPERS" > /sys/kernel/debug/sched_features;
echo "NO_NEW_FAIR_SLEEPERS" > /sys/kernel/debug/sched_features;
echo "NO_NORMALIZED_SLEEPER" > /sys/kernel/debug/sched_features;



# End of fly_engine script
echo "fly_core Tweaks apllied succesfully,Enjoy!!!"








