#!/system/bin/sh
#================================================
#================================================
#=== Fly-On Mod™ RAM manager by Slaid480@XDA ====
#================================================
#================================================ 

#============ Copyright (C) 2013 Salah Abouabdallah(Slaid480)===========#
 
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
 
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
#=======================================================================#

FLY=/data/Fly-On/02ram_manager.log

busybox rm -f $FLY
busybox touch $FLY

echo "# Fly-On Mod™ LOGGING ENGINE" | tee -a $FLY
echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y %H:%M:%S" ) Tweaking minfree values & adj lowmem values..." | tee -a $FLY;

# ADJ Values

echo "0,1,3,5,7,15" > /sys/module/lowmemorykiller/parameters/adj;



# Minfree Values 

mem=`free|grep Mem | awk '{print $2}'`;

if [ "$mem" -lt 512000 ];then
    echo "1408,2816,3755,7040,9387,12288" > /sys/module/lowmemorykiller/parameters/minfree;	
elif [ "$mem" -lt 1024000 ];then
	echo "2560,4096,6144,12288,14336,18432" > /sys/module/lowmemorykiller/parameters/minfree;
else 
	echo "3755,6144,9387,14336,17284,21240" > /sys/module/lowmemorykiller/parameters/minfree;
fi;

echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y %H:%M:%S" ) RAM manager values successfully applied" | tee -a $FLY;
