#!/system/bin/sh
#================================================
#================================================
#=== Fly-On Mod™ RAM manager by Slaid480@XDA ====
#================================================
#================================================ 

#============ Copyright (C) 2013 Salah Abouabdallah(Slaid480)===========#
 
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
 
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
#=======================================================================#

FLY=/data/Fly-On/02ram_manager.log

busybox rm -f $FLY
busybox touch $FLY

echo "# Fly-On Mod™ LOGGING ENGINE" | tee -a $FLY
echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y %H:%M:%S" ) Tweaking minfree values & adj lowmem values..." | tee -a $FLY;
# ADJ Values

echo "0,1,3,5,7,15" > /sys/module/lowmemorykiller/parameters/adj;

# Minfree Values 
echo "2560,4096,7680,14336,17284,21240" > /sys/module/lowmemorykiller/parameters/minfree;

echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y %H:%M:%S" ) RAM manager values successfully applied" | tee -a $FLY;
