#!/system/bin/sh
#================================================
#================================================
#=== Fly-On Mod™ RAM manager by Slaid480@XDA ====
#================================================
#================================================ 

#============ Copyright (C) 2015 Salah Abouabdallah(Slaid480)===========#
 
 see <http://www.gnu.org/licenses/>.
 
#=======================================================================#

FLY=/data/Fly-On/02ram_manager.log

busybox rm -f $FLY
busybox touch $FLY

echo "# Fly-On Mod™ LOGGING ENGINE" | tee -a $FLY
echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y %H:%M:%S" ) Tweaking minfree values & adj lowmem values..." | tee -a $FLY;

# ADJ Values

echo "0,1,3,5,7,15" > /sys/module/lowmemorykiller/parameters/adj;



# Minfree Values 

mem=`free|grep Mem | awk '{print $2}'`;

if [ "$mem" -lt 512000 ];then
    echo "1408,2816,3755,7040,9387,12288" > /sys/module/lowmemorykiller/parameters/minfree;	
elif [ "$mem" -lt 1024000 ];then
	echo "2560,4096,6144,12288,14336,18432" > /sys/module/lowmemorykiller/parameters/minfree;
elif [ "$mem" -lt 1536000 ];then
	echo "3755,6144,9387,14336,17284,21240" > /sys/module/lowmemorykiller/parameters/minfree;
elif [ "$mem" -lt 2048000 ];then
    echo "5632,9216,13234,17920,21605,31860" > /sys/module/lowmemorykiller/parameters/minfree;
else
    echo "6144,11520,16540,22400,28165,41418" > /sys/module/lowmemorykiller/parameters/minfree;  
fi;

# ZRAM tweak

if [ -e /sys/block/zram0/comp_algorithm ]; then
busybox echo "lz4" > /sys/block/zram0/comp_algorithm
fi;

if [ -e /sys/block/zram0 ]; then
busybox echo $((1024*1024*96)) > /sys/block/zram0/disksize
busybox sysctl -e -w vm.swappiness=10
busybox mkswap /dev/block/zram0
busybox swapon /dev/block/zram0
fi;

# Kernel samepage merging tweaks

mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system

chmod 644 /sys/kernel/mm/ksm/*

echo "1" > /sys/kernel/mm/ksm/run
echo "512" > /sys/kernel/mm/ksm/pages_to_scan
echo "1024" > /sys/kernel/mm/ksm/sleep_millisecs


echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y %H:%M:%S" ) RAM manager tweaks successfully applied" | tee -a $FLY;
