#!/system/bin/sh
# Automatic ZipAlign for Fly-On Mod™ by Slaid480
# ZipAlign files in /data that have not been previously

#Interval between ZipAlign runs, in seconds, 172800=48 hours
RUN_EVERY=172800

LOG_FILE=/data/zipalign_data.log
    if [ -e $LOG_FILE ]; then
      rm $LOG_FILE;
    fi;


echo "Starting Automatic ZipAlign $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE;
    for apk in /data/app/*.apk ; do
  zipalign -c 4 $apk;
  ZIPCHECK=$?;
  if [ $ZIPCHECK -eq 1 ]; then
    echo ZipAligning $(basename $apk)  | tee -a $LOG_FILE;
    zipalign -f 4 $apk /cache/$(basename $apk);
      if [ -e /cache/$(basename $apk) ]; then
        cp -f -p /cache/$(basename $apk) $apk  | tee -a $LOG_FILE;
        rm /cache/$(basename $apk);
      else
        echo ZipAligning $(basename $apk) Failed  | tee -a $LOG_FILE;
      fi;
  else
    echo ZipAlign already completed on $apk  | tee -a $LOG_FILE;
  fi;
       done;
echo "Automatic ZipAlign finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE;